export const tn = {
    email: 'email',
    password: 'password',
    login: 'login',
    signUp: 'signUp',
    username: 'username',
    settings: 'settings',
    colorTheme: 'colorTheme',
    dark: 'dark',
    light: 'light',
    language: 'language',
    english: 'english',
    turkish: 'turkish',
    signOut: 'signOut',
    dontHaveAccount: 'dontHaveAccount',
    alreadyHaveAccount: 'alreadyHaveAccount',
    home: 'home',
    addPill: 'addPill',
    PillName: 'PillName',
    kind: 'kind',
    startDate: 'startDate',
    today: 'today',
    url: 'url',
    note: 'note',
    add: 'add',
    edit: 'edit',
    detail: 'detail',
    adddetail: 'adddetail',
    save: 'save',
};

export const english = {
    [tn.email]: 'E-mail',
    [tn.password]: 'Password',
    [tn.login]: 'Login',
    [tn.signUp]: 'Sign Up',
    [tn.username]: 'Username',
    [tn.settings]: 'Settings',
    [tn.colorTheme]: 'Color Theme',
    [tn.dark]: 'Dark',
    [tn.light]: 'Light',
    [tn.language]: 'Language',
    [tn.english]: 'English',
    [tn.turkish]: 'Türkçe',
    [tn.signOut]: 'Sign Out',
    [tn.dontHaveAccount]: "Don't have account?",
    [tn.alreadyHaveAccount]: 'Already have account?',
    [tn.home]: 'Home',
    [tn.pillusage]: 'Add Pill Usage',
    [tn.PillName]: 'Pill Name',
    [tn.kind]: 'Kind',
    [tn.startDate]: 'Start Date',
    [tn.today]: 'Today',
    [tn.url]: 'URL',
    [tn.note]: 'Note',
    [tn.add]: 'Add',
    [tn.edit]: 'Edit',
    [tn.detail]: 'Detail',
    [tn.addDetail]: 'Add Detail',
    [tn.save]: 'Save',
}

export const turkish = {
    [tn.email]: 'E-posta',
    [tn.password]: 'Şifre',
    [tn.login]: 'Giriş Yap',
    [tn.signUp]: 'Kayıt Ol',
    [tn.username]: 'Kullanıcı Adı',
    [tn.settings]: 'Ayarlar',
    [tn.colorTheme]: 'Renk Teması',
    [tn.dark]: 'Karanlık',
    [tn.light]: 'Aydınlık',
    [tn.language]: 'Dil',
    [tn.english]: 'English',
    [tn.turkish]: 'Türkçe',
    [tn.signOut]: 'Çıkış Yap',
    [tn.dontHaveAccount]: 'Hesabınız yok mu?',
    [tn.alreadyHaveAccount]: 'Zaten hesabınız var mı?',
    [tn.home]: 'Anasayfa',
    [tn.addPill]: 'Yeni ilaç ekle',
    [tn.pillName]: 'İlaç Adı',
    [tn.kind]: 'Tür',
    [tn.startDate]: 'BaşlamaTarihi',
    [tn.today]: 'Bugün',
    [tn.url]: 'URL',
    [tn.note]: 'Not',
    [tn.add]: 'Ekle',
    [tn.edit]: 'Düzenle',
    [tn.detail]: 'Detay',
    [tn.adddetail]: 'Detay ekle',
    [tn.save]: 'Kaydet',
}